version: '2'

services:
  kafka:
    restart: always
    build: ./kafka
    ports:
      # expose kafka broker (9092) and zookeeper (2181)
      - "9092:9092"
      - "2181:2181"

  producer:
    restart: always
    build: ./producer
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres

  consumer:
    restart: always
    build: ./consumer
    depends_on:
      - kafka
      - postgres

  postgres:
    restart: always
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
