version: '2'

services:
  producer:
    restart: always
    build: ./producer
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    volumes:
      - ./producer/producer:/producer
    environment:
      ENVIRONMENT: "DOCKER-COMPOSE"
      POSTGRES_PASSWORD: "example"
#    entrypoint: sleep infinity  # if we need to debug

  consumer:
    restart: always
    build: ./consumer
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./consumer/consumer:/consumer
    environment:
      ENVIRONMENT: "DOCKER-COMPOSE"
      HOST: "0.0.0.0"
      PORT: "8000"
      PRODUCER_HOST: "producer"
      PRODUCER_PORT: "8002"
    stdin_open: true
    tty: true
#    entrypoint: sleep infinity  # if we need to debug


  postgres:
    restart: always
    build: ./postgres
    ports:
      - "5432:5432"
