version: '2'

services:
  producer:
    restart: always
    build: ./producer
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  consumer:
    restart: always
    build: ./consumer
    ports:
      - "8000:8000"

  postgres:
    restart: always
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
