version: '2'

services:
  producer:
    restart: always
    build: ./producer
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    volumes:
      - ./producer/producer:/producer
    environment:
      ENVIRONMENT: "docker-compose"
    entrypoint: sleep infinity

  consumer:
    restart: always
    build: ./consumer
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./consumer/consumer:/consumer
    environment:
      PRODUCER_HOST: "producer"
      PRODUCER_PORT: "8002"
    entrypoint: sleep infinity

  postgres:
    restart: always
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
