version: '2'

services:
  producer:
    restart: always
    build:
      context: .
      dockerfile: sequence_search/producer/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    volumes:
      - ./:/rnacentral
    environment:
      ENVIRONMENT: "DOCKER-COMPOSE"
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: "example"
    # the following options are used to connect to pdb debugger, running within the container
    # to connect to it, run 'docker attach sequencesearchdevops_producer_1'
    stdin_open: true
    tty: true
#    entrypoint: sleep infinity  # replace entrypoint with this command, if you need to debug it

  consumer:
    restart: always
    build:
      context: .
      dockerfile: sequence_search/consumer/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./:/rnacentral
    environment:
      ENVIRONMENT: "DOCKER-COMPOSE"
      HOST: "0.0.0.0"
      PORT: "8000"
      PRODUCER_HOST: "producer"
      PRODUCER_PORT: "8002"
    stdin_open: true
    tty: true
    depends_on:
      - producer
#    entrypoint: sleep infinity  # if we need to debug

  postgres:
    restart: always
    build: ./postgres
    ports:
      - "5432:5432"
