# file: producer/tasks/build_frontend.yml

  - name: Remove node_modules, copied over from local machine (if any)
    shell:
      chdir: /srv/producer/producer/static
      cmd: rm -rf node_modules

  - name: Remove package-lock.json, copied over from local machine (if any)
    shell:
      chdir: /srv/producer/producer/static
      cmd: rm package-lock.json

  - name: Install node_modules
    shell:
      chdir: /srv/producer/producer/static
      cmd: "npm install"
    become: false

  - name: Clean dist directory
    shell:
     chdir: /srv/producer/producer/static
     cmd: "npm run clean"

  - name: Build frontend code bundle in dist
    shell:
      chdir: /srv/producer/producer/static
      cmd: "npm run build"
