# file: producer/tasks/main.yml

---
  # This role is related to producer installation
  - import_tasks: install_deps.yml
    tags: [ producer-install-deps ]

  - import_tasks: rsync.yml
    tags: [ producer-rsync ]

  - name: Install requirements
    shell: /usr/local/bin/pip install -r requirements.txt
    args:
      chdir: /srv/sequence_search

  - import_tasks: logs.yml
    tags: [ producer-logs ]

  - import_tasks: build_frontend.yml
    tags: [ producer-frontend ]

  - name: Apply migrations to the database
    shell:
      chdir: /srv/sequence_search
      cmd: ENVIRONMENT=PRODUCTION python36 -m sequence_search.db

  - import_tasks: restart.yml
    tags: [ producer-restart ]
