---
  # This role is related to producer installation
  - name: Enable epel repository
    yum_repository:
      name: epel
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      enabled: yes
      state: present
      description: epel repostiory
      gpgcheck: no

  - name: Install yum dependencies
    yum:
      name:
      - curl
      - gcc
      - git
      - libaio
      - openssl
      - openssl-devel
      - tar
      - unzip
      - wget
      - zlib-devel
      - gcc-c++
      - make
      - python36
      - python36-devel
      - python36-setuptools
      - nodejs

  - name: Install pip3
    shell: easy_install-3.6 pip

  - name: Rsync aiohttp code
    synchronize:
      src: ../../../producer
      dest: /srv

  - name: Chown aiohttp code
    file:
      path: /srv/producer
      owner: centos
      group: centos
      mode: 0755
      recurse: yes

  - name: Install requirements
    shell: /usr/local/bin/pip install -r requirements.txt
    args:
      chdir: /srv/producer

  - name: Create logs directory
    file:
      path: /var/log/gunicorn
      state: directory
      owner: centos
      group: centos
      mode: 0755

  - name: Install node_modules
    shell:
      chdir: /srv/producer/producer/static
      cmd: "npm install"

  - name: Clean dist directory
    shell:
     chdir: /srv/producer/producer/static
     cmd: "npm run clean"

  - name: Build frontend code bundle in dist
    shell:
      chdir: /srv/producer/producer/static
      cmd: "npm run build"

  - name: Kill running instances of producer service
    shell: "sudo kill $(ps -ef | grep -v grep | grep -w gunicorn | awk '{print $2}')"
    ignore_errors: yes

  - name: Run producer service
    shell:
      chdir: /srv/producer
      cmd: /usr/local/bin/gunicorn producer.main:app --daemon --bind 0.0.0.0:8002 --worker-class aiohttp.worker.GunicornWebWorker --access-logfile /var/log/gunicorn/access_log --error-logfile /var/log/gunicorn/error_log --env ENVIRONMENT=PRODUCTION --log-level=DEBUG --timeout 120

#  - name: Install lvm2
#    yum:
#      name: lvm2
#      state: latest
#
#  - name: Add Docker repo
#    get_url:
#      url: https://download.docker.com/linux/centos/docker-ce.repo
#      dest: /etc/yum.repos.d/docer-ce.repo
#    become: yes
#
#  - name: Enable Docker Edge repo
#    ini_file:
#      dest: /etc/yum.repos.d/docer-ce.repo
#      section: 'docker-ce-edge'
#      option: enabled
#      value: 0
#    become: yes
#
#  - name: Enable Docker Test repo
#    ini_file:
#      dest: /etc/yum.repos.d/docer-ce.repo
#      section: 'docker-ce-test'
#      option: enabled
#      value: 0
#    become: yes
#
#  - name: Install Docker
#    package:
#      name: docker-ce
#      state: latest
#    become: yes
#
#  - name: Start Docker service
#    service:
#      name: docker
#      state: started
#      enabled: yes
#    become: yes
#
#  - name: Add user vagrant to docker group
#    user:
#      name: vagrant
#      groups: docker
#      append: yes
#    become: yes
