# file: producer/tasks/restart.yml

  - name: Get running processes
    shell: "ps -ef | grep -v grep | grep -w producer.main | awk '{print $2}'"
    #    shell: "sudo kill $(ps -ef | grep -v grep | grep -w producer.main | awk '{print $2}')"
    register: running_processes

  - name: Kill running processes
    shell: "kill {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"

  # copied over from: https://stackoverflow.com/questions/46515704/how-to-kill-a-running-process-using-ansible
  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes
    register: killed_processes

  - name: Force kill stuck processes
    shell: "kill -9 {{ item }}"
    with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"

  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes

  - name: Run producer service
    shell:
      chdir: /srv/producer
#      cmd: /usr/local/bin/gunicorn producer.main:app --daemon --bind 0.0.0.0:8002 --worker-class aiohttp.worker.GunicornWebWorker --access-logfile /var/log/gunicorn/access_log --error-logfile /var/log/gunicorn/error_log --env ENVIRONMENT=PRODUCTION --log-level=DEBUG --timeout 120
      cmd: ENVIRONMENT=PRODUCTION nohup python36 -m producer.main &> /var/log/gunicorn/access_log &