# file: producer/tasks/rsync.yml

  - name: Rsync aiohttp code
    synchronize:
      src: ../../../../sequence_search
      dest: /srv

  - name: Chown aiohttp code
    file:
      path: /srv/sequence_search
      owner: centos
      group: centos
      mode: 0755
      recurse: yes