---
  # Most of the subnet in our case is not visible from outside world
  # so we need to use a jumphost/bastion to ssh to it and from it
  # to ssh to private machines. To do this, we need to install private
  # key on bastion host.
  - name: Install ssh key
    copy:
      src: ../terraform/terraform_rsa
      dest: /home/centos/.ssh/id_rsa
      owner: centos
      group: centos
      mode: 0400