---
- hosts: load_balancer
  remote_user: centos
  become: yes
  become_user: root
  gather_facts: True
  roles:
    - role: ansible-role-nginx
      nginx_sites:
        upstream:
          template: upstream.conf.j2