# file: consumer/tasks/install_deps.yml

  - name: Enable epel repository
    yum_repository:
      name: epel
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      enabled: yes
      state: present
      description: epel repostiory
      gpgcheck: no

  - name: Install yum dependencies
    yum:
      name:
      - curl
      - gcc
      - git
      - libaio
      - openssl
      - openssl-devel
      - tar
      - unzip
      - wget
      - zlib-devel
      - gcc-c++
      - make
      - python36
      - python36-devel
      - python36-setuptools
      - postgresql.x86_64

  - name: Install pip3
    shell: easy_install-3.6 pip