---
  # This role is about consumer installation

  - name: Enable epel repository
    yum_repository:
      name: epel
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      enabled: yes
      state: present
      description: epel repostiory
      gpgcheck: no
    tags: [ install-deps ]

  - name: Install yum dependencies
    yum:
      name:
      - curl
      - gcc
      - git
      - libaio
      - openssl
      - openssl-devel
      - tar
      - unzip
      - wget
      - zlib-devel
      - gcc-c++
      - make
      - python36
      - python36-devel
      - python36-setuptools
      - postgresql.x86_64
    tags: [ install-deps ]

  - name: Install pip3
    shell: easy_install-3.6 pip
    tags: [ install-deps ]



  - name: Install nhmmer
    shell: |
      curl -OL http://eddylab.org/software/hmmer/hmmer-3.2.1.tar.gz
      tar -zxvf hmmer-3.2.1.tar.gz
      cd hmmer-3.2.1
      ./configure --prefix /usr/local
      make
      make install
      cd easel; make install



  - name: Rsync aiohttp code
    synchronize:
      src: ../../../../sequence_search
      dest: /srv
      rsync_opts:
        - "--exclude=/sequence_search/consumer/databases.iso"
        - "--exclude=/sequence_search/consumer/databases"
        - "--exclude=/sequence_search/consumer/databases_back"
        - "--exclude=/sequence_search/consumer/queries/*.fasta"
        - "--exclude=/sequence_search/consumer/results/*.fasta"
    tags: [ quick ]



  - name: Delete logs directory
    file:
      path: /var/log/gunicorn
      state: absent
    ignore_errors: yes
    tags: [ logs ]

  - name: Create logs directory
    file:
      path: /var/log/gunicorn
      state: directory
      owner: centos
      group: centos
      mode: 0755
    tags: [ logs ]



  - name: Delete queries directory
    file:
      path: /srv/sequence_search/consumer/queries
      state: absent
    tags: [ queries, quick ]

  - name: Create queries directory
    file:
      path: /srv/sequence_search/consumer/queries
      state: directory
      owner: centos
      group: centos
      mode: 0755
    tags: [ queries, quick ]



  - name: Delete results directory
    file:
      path: /srv/sequence_search/consumer/results
      state: absent
    tags: [ results, quick ]

  - name: Create results directory
    file:
      path: /srv/sequence_search/consumer/results
      state: directory
      owner: centos
      group: centos
      mode: 0755
    tags: [ results, quick ]



  - name: Umount volume for databases (so that chown doesn't complain)
    mount:
      path: /srv/sequence_search/consumer/databases
      src: /dev/vdb
      fstype: iso9660
      state: unmounted
    ignore_errors: yes
    tags: [ quick ]

# Ansible chown is slow, cause it checks ownership before assigning it - so just run chown imperatively
# https://groups.google.com/forum/#!topic/ansible-project/2O5u8GIZ5Rw

# Alternatively:
#    file:
#      path: /srv/sequence_search
#      owner: centos
#      group: centos
#      mode: 0755
#      recurse: yes

  - name: Chown aiohttp code
    command: "chown -R centos:centos /srv/sequence_search"
    changed_when: false
    tags: [ quick ]

  - name: Chmod aiohttp code
    command: "chmod 755 /srv/sequence_search"
    tags: [ quick ]


  - name: Install pip3 requirements
    shell: /usr/local/bin/pip install -r requirements.txt
    args:
      chdir: /srv/sequence_search

  - name: Mount volume for databases
    mount:
      path: /srv/sequence_search/consumer/databases
      src: /dev/vdb
      fstype: iso9660
      state: mounted
    tags: [ quick ]



  - name: Get running processes
#    shell: "sudo kill $(ps -ef | grep -v grep | grep -w gunicorn | awk '{print $2}')"
    shell: "sudo kill $(ps -ef | grep -v grep | grep -w consumer | awk '{print $2}')"
    register: running_processes
    ignore_errors: yes
    tags: [ restart, quick ]

  - name: Kill running processes
    shell: "kill {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"
    tags: [ restart, quick ]

  # copied over from: https://stackoverflow.com/questions/46515704/how-to-kill-a-running-process-using-ansible
  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes
    register: killed_processes
    tags: [ restart, quick ]

  - name: Force kill stuck processes
    shell: "kill -9 {{ item }}"
    with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
    tags: [ restart, quick ]

  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes
    tags: [ restart, quick ]

  - name: Run consumer service
    shell:
      chdir: /srv
#      cmd: /usr/local/bin/gunicorn consumer.main:app --daemon --bind 0.0.0.0:8000 --worker-class aiohttp.worker.GunicornWebWorker --access-logfile /var/log/gunicorn/access_log --error-logfile /var/log/gunicorn/error_log --env ENVIRONMENT=PRODUCTION --log-level=DEBUG
      cmd: ENVIRONMENT=PRODUCTION nohup python36 -m sequence_search.consumer &> /var/log/gunicorn/access_log &
    tags: [ restart, quick ]
