---
  # This role is about consumer installation

  - import_tasks: install_deps.yml
    tags: [ consumer-install-deps ]

  - name: Rsync aiohttp code
    synchronize:
      src: ../../../../sequence_search
      dest: /srv
      rsync_opts:
        - "--exclude=/sequence_search/consumer/databases.iso"
        - "--exclude=/sequence_search/consumer/databases"
        - "--exclude=/sequence_search/consumer/databases_back"
        - "--exclude=/sequence_search/consumer/queries/*.fasta"
        - "--exclude=/sequence_search/consumer/results/*.fasta"

  - import_tasks: logs.yml
    tags: [ consumer-logs ]

  - import_tasks: queries.yml
    tags: [ consumer-queries ]

  - import_tasks: results.yml
    tags: [ consumer-results ]

  - import_tasks: logs.yml
    tags: [ consumer-logs ]

  - name: Umount volume for databases (so that chown doesn't complain)
    mount:
      path: /srv/sequence_search/consumer/databases
      src: /dev/vdb
      fstype: iso9660
      state: unmounted
    ignore_errors: yes

  - name: Chown aiohttp code
    file:
      path: /srv/sequence_search
      owner: centos
      group: centos
      mode: 0755
      recurse: yes

  - name: Install pip3 requirements
    shell: /usr/local/bin/pip install -r requirements.txt
    args:
      chdir: /srv/sequence_search/consumer

  - name: Mount volume for databases
    mount:
      path: /srv/sequence_search/consumer/databases
      src: /dev/vdb
      fstype: iso9660
      state: mounted

  - import_tasks: restart.yml
    tags: [ consumer-restart ]
