# file: consumer/tasks/queries.yml

  - name: Delete queries directory
    file:
      path: /srv/sequence_search/consumer/queries
      state: absent

  - name: Create queries directory
    file:
      path: /srv/sequence_search/consumer/queries
      state: directory
      owner: centos
      group: centos
      mode: 0755