---
- hosts: monitor
  remote_user: centos
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "../terraform/sequence_search_rsa"
    floating_ip: "{{ lookup('pipe', 'cd ../terraform && terraform output floating_ip') }}"
  roles:
    - monitor
    - ssh
    - iptables
