---
# Playbook to update the jobs table and allow users to search for a sequence that already has results in the database
- hosts: postgres
  remote_user: centos
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "../terraform/sequence_search_rsa"
  tasks:
    - name: Update jobs to allow users to search for any sequence
      command: psql -U docker -c "UPDATE jobs SET result_in_db = NOT result_in_db WHERE result_in_db = TRUE" producer
