---
  # Added by cribas
  - name: Copy the script to do backups
    copy: src=../postgres/backup.sh dest=/etc/cron.daily/backup.sh owner=postgres group=postgres mode=0755

  - name: Create backup directory
    file:
      path: /backup
      state: directory
      owner: postgres
      mode: '0777'

  - name: Set Time Zone
    timezone:
      name: Europe/London