---
- name: kafka
  gather_facts: No
  hosts: kafka
  tasks:
    - name: Download kafka binaries
      get-url:
        url: https://www.apache.org/dyn/closer.cgi?path=/kafka/1.1.0/kafka_2.11-1.1.0.tgz
        dest: /usr/local/bin
        become: true

    - name: Untar kafka
      unarchive:
        src: /usr/local/bin/kafka_2.11-1.1.0.tgz
        dest: /usr/local/bin

    - name: Run Zookeeper
      shell: nohup /usr/local/bin/kafka_2.11-1.1.0/bin/zookeeper-server-start.sh config/zookeeper.properties &

    - name: Run Kafka
      shell: nohup /usr/local/bin/kafka_2.11-1.1.0/bin/kafka-server-start.sh config/server.properties &
